#!/usr/bin/env python3
"""Generate caramel_activation.h - shared bit-exact fixed-point activation LUTs.

The emitted header is byte-identical in bark/ and caramel_lang/. Pure integer
(int64) evaluation, C and C++ compatible, no floating point at runtime, so the
worker (-mno-sse) and the lang interpreter compute identical results.
"""
import math

IN_SCALE = 1000       # input fixed-point:  real = xf / 1000
OUT_SCALE = 1000000    # table value scale:  f    = v  / 1e6
STEP = 64              # xf units per bucket (0.064 real)
MAX_QRES = 9

def table(fn, lo_real, hi_real, clamp_lo, clamp_hi):
    lo = int(round(lo_real * IN_SCALE))
    hi = int(round(hi_real * IN_SCALE))
    assert (hi - lo) % STEP == 0
    n = (hi - lo) // STEP
    vals = []
    for k in range(n + 1):
        xf = lo + k * STEP
        r = xf / IN_SCALE
        v = int(round(fn(r) * OUT_SCALE))
        v = max(clamp_lo, min(clamp_hi, v))
        vals.append(v)
    return lo, n, vals

def sigmoid(r):
    # numerically stable
    if r >= 0:
        z = math.exp(-r); return 1.0 / (1.0 + z)
    z = math.exp(r); return z / (1.0 + z)

sig_lo, sig_n, sig_vals = table(sigmoid, -16, 16, 0, OUT_SCALE)
tanh_lo, tanh_n, tanh_vals = table(math.tanh, -8, 8, -OUT_SCALE, OUT_SCALE)
exp_lo, exp_n, exp_vals = table(math.exp, -16, 0, 0, OUT_SCALE)

def emit_array(name, vals):
    out = [f"static const int32_t {name}[{len(vals)}] = {{"]
    line = "   "
    for v in vals:
        piece = f" {v},"
        if len(line) + len(piece) > 78:
            out.append(line); line = "   "
        line += piece
    out.append(line)
    out.append("};")
    return "\n".join(out)

H = f"""\
/*
 * caramel_activation.h - shared bit-exact fixed-point activation kernels.
 *
 * GENERATED by tools/gen_activation.py - identical bytes in bark/ and
 * caramel_lang/. Do NOT edit by hand; regenerate and copy into both repos.
 *
 * Pure integer (int64) evaluation, C and C++ compatible, no floating point at
 * runtime. This is what makes remote (worker, -mno-sse) and local (lang
 * interpreter) results BYTE-IDENTICAL, which --verify requires. Semantics are
 * normative: see PROTOCOL_SPEC.md 6.5 "Activation semantics".
 *
 * Convention: a register element i encodes the real value i / 10^q where
 * q = quantres (decimal fixed-point, quantizer.h). Activations decode i -> r,
 * apply f, and re-encode round(f(r) * 10^q). Tables sample f on a uniform grid
 * (input scale {IN_SCALE}, step {STEP}) and store round(f * {OUT_SCALE}); lookup
 * linearly interpolates and rounds half-away-from-zero. Inputs beyond the table
 * domain saturate to the end entries. Requires 0 <= q <= {MAX_QRES}.
 */
#ifndef CARAMEL_ACTIVATION_H
#define CARAMEL_ACTIVATION_H

#include <stdint.h>

#define CACT_IN_SCALE   {IN_SCALE}
#define CACT_OUT_SCALE  {OUT_SCALE}
#define CACT_STEP       {STEP}
#define CACT_MAX_QRES   {MAX_QRES}

typedef struct {{
    int32_t        lo;    /* input-fixed (scale CACT_IN_SCALE) of vals[0] */
    int32_t        n;     /* bucket count; vals has n+1 entries           */
    const int32_t *vals;  /* f sampled on the grid, scale CACT_OUT_SCALE  */
}} cact_table_t;

{emit_array("cact_sigmoid_vals", sig_vals)}

{emit_array("cact_tanh_vals", tanh_vals)}

{emit_array("cact_exp_vals", exp_vals)}

static const cact_table_t CACT_SIGMOID = {{ {sig_lo}, {sig_n}, cact_sigmoid_vals }};
static const cact_table_t CACT_TANH    = {{ {tanh_lo}, {tanh_n}, cact_tanh_vals }};
static const cact_table_t CACT_EXP     = {{ {exp_lo}, {exp_n}, cact_exp_vals }};

/* round(a / b) for b > 0, half away from zero. */
static inline int64_t cact_rdiv(int64_t a, int64_t b)
{{
    return (a >= 0) ? (a + b / 2) / b : -((-a + b / 2) / b);
}}

/* 10^q as int64; 0 (an out-of-range sentinel) if q is outside [0,MAX_QRES]. */
static inline int64_t cact_pow10(int32_t q)
{{
    int64_t m = 1;
    int32_t k;
    if (q < 0 || q > CACT_MAX_QRES) {{ return 0; }}
    for (k = 0; k < q; k++) {{ m *= 10; }}
    return m;
}}

/* Interpolate table t at input-fixed xf (scale CACT_IN_SCALE); returns f in
 * CACT_OUT_SCALE units. Saturates to the end entries outside the domain. */
static inline int64_t cact_lookup(const cact_table_t *t, int64_t xf)
{{
    int64_t hi = (int64_t)t->lo + (int64_t)CACT_STEP * t->n;
    int64_t rel, k, frac, v0, v1;
    if (xf <= t->lo) {{ return t->vals[0]; }}
    if (xf >= hi)    {{ return t->vals[t->n]; }}
    rel  = xf - t->lo;
    k    = rel / CACT_STEP;
    frac = rel - k * CACT_STEP;
    v0   = t->vals[k];
    v1   = t->vals[k + 1];
    return v0 + cact_rdiv((v1 - v0) * frac, CACT_STEP);
}}

/* sigmoid/tanh: register value i (scale M = 10^q) -> register value (scale M).
 * M must be nonzero (caller validates quantres). */
static inline int32_t cact_unary(const cact_table_t *t, int32_t i, int64_t M)
{{
    int64_t xf = cact_rdiv((int64_t)i * CACT_IN_SCALE, M);
    int64_t f  = cact_lookup(t, xf);
    return (int32_t)cact_rdiv(f * M, CACT_OUT_SCALE);
}}

/* exp for softmax: register delta d (= i - max, scale M, <= 0) -> e^r in
 * CACT_OUT_SCALE units. */
static inline int64_t cact_exp_fixed(int64_t d, int64_t M)
{{
    int64_t xf = cact_rdiv(d * CACT_IN_SCALE, M);
    return cact_lookup(&CACT_EXP, xf);
}}

/* softmax over a gathered axis-group: `len` register values `in` (scale M) ->
 * `len` normalized register values `out` (scale M). Two-pass (max-subtract for
 * stability, then normalize); e_j recomputed rather than buffered so no scratch
 * is needed. Bit-exact: all arithmetic via the shared helpers above. */
static inline void cact_softmax_group(const int32_t *in, int32_t *out,
                                      int32_t len, int64_t M)
{{
    int32_t j;
    int32_t mx = in[0];
    int64_t sum = 0;
    for (j = 1; j < len; j++) {{ if (in[j] > mx) {{ mx = in[j]; }} }}
    for (j = 0; j < len; j++) {{
        sum += cact_exp_fixed((int64_t)in[j] - (int64_t)mx, M);
    }}
    for (j = 0; j < len; j++) {{
        int64_t e = cact_exp_fixed((int64_t)in[j] - (int64_t)mx, M);
        out[j] = (int32_t)cact_rdiv(e * M, sum);
    }}
}}

#endif /* CARAMEL_ACTIVATION_H */
"""
import sys
sys.stdout.write(H)
